### ISSUE TITLE
linked Bootstrap 4 CSS to param.html but param.css not working

### ISSUE THREAD

**Issue by PrabhuKGP** [coderbabu10/Magical-Flute#15]
When I added bootstrap 4 CSS to the code, only one of the 2 stylesheets are working.(the one present first).What could be the error?

**Comment by SuvamPrasd** [comment]
Please send the screenshots.

**Comment by PrabhuKGP** [comment]
![Annotation 2019-12-09 092512](https://user-images.githubusercontent.com/54051239/70406252-1f292d00-1a66-11ea-80d9-4b0f17761a37.png)

**Comment by PrabhuKGP** [comment]
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="param1.css">`

**Comment by PrabhuKGP** [comment]
![Annotation 2019-12-09 092924](https://user-images.githubusercontent.com/54051239/70406351-6d3e3080-1a66-11ea-9ede-80327e9b5712.png)

**Comment by PrabhuKGP** [comment]
If I reverse the order of stylesheets, param1.css is working and bootstrap isn't working

**Comment by SuvamPrasd** [comment]
Boostrap css should be declared first and then after custom css file.
Actually the Boostrap-4 css is overriding the custom css code.

**Comment by SuvamPrasd** [comment]
Can you tell me what are changes you are doing in the CSS?

**Comment by PrabhuKGP** [comment]
> Boostrap css should be declared first and then after custom css file.
> Actually the Boostrap-4 css is overr

**Comment by PrabhuKGP** [comment]
instead of having a seperate page for contact ,we can add contact and about in the footer of the home page itself

**Comment by SuvamPrasd** [comment]
yeah. But Someone has already done a pull request but not merged in the actual code.

**Comment by SuvamPrasd** [comment]
You can work on the contact information.

**Comment by PrabhuKGP** [comment]
ok

**Comment by PrabhuKGP** [comment]
Should we make a seperate page for contacts, it will be better if it's present at the bottom of home page

**Comment by SuvamPrasd** [comment]
We'll make a separate webpage for the contact.
